# This file is autogenerated from update.py in the same directory.
{
  dev = {
    version = "35.0.1883.0";
    url = "http://commondatastorage.googleapis.com/chromium-browser-official/chromium-35.0.1883.0.tar.xz";
    sha256 = "0qbv6prxl18y5824pfd13ng9798g561gzb6nypwp502hqr45jvb6";

    deb_amd64 = {
      url = "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-unstable/google-chrome-unstable_35.0.1883.0-1_amd64.deb";
      sha1 = "f768c4a5872f619ac9af9c8e695fdf9b35bba363";
    };

    deb_i386 = {
      url = "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-unstable/google-chrome-unstable_35.0.1883.0-1_i386.deb";
      sha1 = "dc68dcebdc43b50f433e0e583f96a92681df9e5d";
    };
  };
  beta = {
    version = "34.0.1847.60";
    url = "http://commondatastorage.googleapis.com/chromium-browser-official/chromium-34.0.1847.60.tar.xz";
    sha256 = "1na5d6z4a0wkabn7cj62vyiv3mmvcb6qdvrkyy6fj79h7gk2hb7k";

    deb_amd64 = {
      url = "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-beta/google-chrome-beta_34.0.1847.60-1_amd64.deb";
      sha1 = "ac874cacd4cd50d3a5a5053cfb012036faf8de61";
    };

    deb_i386 = {
      url = "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-beta/google-chrome-beta_34.0.1847.60-1_i386.deb";
      sha1 = "ae477f25d44d357b09545d48fc2824af2ffd9cb2";
    };
  };
  stable = {
    version = "33.0.1750.152";
    url = "http://commondatastorage.googleapis.com/chromium-browser-official/chromium-33.0.1750.152.tar.xz";
    sha256 = "0byc23vwn9alsva0jqvwvgnbx2bm7x48m3jln02y4fpf1f265m4z";

    deb_amd64 = {
      url = "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_33.0.1750.152-1_amd64.deb";
      sha1 = "f6502f0875bdf605283ce2662bae211f0dc40e7d";
    };

    deb_i386 = {
      url = "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_33.0.1750.152-1_i386.deb";
      sha1 = "5808d5c62e9ed1b5495fb2678079a45f58bc43bf";
    };
  };
}
